
Train transforms: [<utils.data_utils.PointcloudToTensor object at 0x0000024BF717E300>, <utils.data_utils.RandomSample object at 0x0000024BF6BC5FA0>, <utils.data_utils.AugmScale object at 0x0000024BF87EF9E0>, <utils.data_utils.AugmRotate object at 0x0000024BF88576E0>, <utils.data_utils.AugmRotatePerturbation object at 0x0000024BF76AE720>, <utils.data_utils.AugmTranslate object at 0x0000024BF749A720>, <utils.data_utils.AugmJitter object at 0x0000024BF749A330>]
Traceback (most recent call last):
  File "C:\Users\matti\Desktop\AML\Codice\nostro\SemNov_AML_DAAI_23-24-main\classifiers\trainer_cla_md.py", line 734, in <module>
    main()
  File "C:\Users\matti\Desktop\AML\Codice\nostro\SemNov_AML_DAAI_23-24-main\classifiers\trainer_cla_md.py", line 725, in main
    train(args, config)
  File "C:\Users\matti\Desktop\AML\Codice\nostro\SemNov_AML_DAAI_23-24-main\classifiers\trainer_cla_md.py", line 302, in train
    train_loader, test_loader = get_md_loaders(opt)
                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matti\Desktop\AML\Codice\nostro\SemNov_AML_DAAI_23-24-main\classifiers\trainer_cla_md.py", line 157, in get_md_loaders
    train_data = ModelNet40_OOD(  # sampling performed as dataugm
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matti\Desktop\AML\Codice\nostro\SemNov_AML_DAAI_23-24-main\datasets\modelnet.py", line 230, in __init__
    for line in open(
                ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './3D_OS_release_data\\modelnet40_normal_resampled\\./3D_OS_release_data\\modelnet40_normal_resampled\\modelnet40_train.txt'